periodics:
- name: periodic-mirror-images
  decorate: true
  interval: 24h
  extra_refs:
  - org: rajaskakodkar
    repo: tanzu-test-infra
    base_ref: main
  annotations:
    testgrid-dashboards: tce
    testgrid-tab-name: periodics
  labels:
    preset-dind-enabled: "true"
  spec:
    containers:
    - image: public.ecr.aws/t0q8k6g2/vagator/test-image:v20222903-be6db42
      command:
      - /usr/local/bin/run.sh
      args:
      - rajaskakodkar
      - tanzu-test-infra
      - chmod +x ./scripts/mirror-images/sync-upstream-images-with-ecr.sh && ./scripts/mirror-images/sync-upstream-images-with-ecr.sh
      securityContext:
        privileged: true
